### PR TITLE
Update valacdos data with Modulus Weight Table Data from 2020-04-06

### PR DESCRIPTION
**Pull request by aclemons**
https://www.vocalink.com/tools/modulus-checking/
https://www.vocalink.com/media/4369/valacdos.txt

### CODE REVIEW

**Comment by ball-hayden** [comment]
Thanks. Please could you also update the date in the README (line 14)?

**Comment by aclemons** [comment]
Oh yes, I missed that.

Should be updated now.

**Review by ball-hayden — APPROVED** [review]
Great. Thank you.

**Comment by ball-hayden** [comment]
New version released.

**Pull request merged**
