### PR TITLE
Update modulus weight table data – valid from 2019-05-27

### PR DESCRIPTION
**Pull request by dbourguignon**
Updating the table data

Thanks 👍

### CODE REVIEW

**Comment by ball-hayden** [comment]
Thanks. I'll push a new version to rubygems when I'm able

**Comment by dbourguignon** [comment]
Thanks a lot, that will be very helpful!

**Comment by ball-hayden** [comment]
Finally sorted. Sorry for the delay.

**Comment by dbourguignon** [comment]
Thank you so much!

**Pull request merged**
